#!/usr/bin/env bash

set -euo pipefail

OUTPUT_FILE="${1:-/Users/pvalastro/Desktop/Peters-data-day-one.md}"
INTERVAL_SECONDS="${2:-300}"
MAX_ENTRIES="${3:-90}"
TRANSCRIPTS_DIR="/Users/pvalastro/.cursor/projects/Users-pvalastro-Desktop-cursor-project/agent-transcripts"

mkdir -p "$(dirname "$OUTPUT_FILE")"

if [ ! -f "$OUTPUT_FILE" ]; then
  {
    echo "# Peter's Data Day One"
    echo
    echo "Generated by peter-usage-monitor.sh"
    echo
  } >>"$OUTPUT_FILE"
fi

frontmost_app() {
  osascript -e 'tell application "System Events" to get name of first application process whose frontmost is true' 2>/dev/null || echo "Unknown"
}

browser_context() {
  osascript -e 'tell application "System Events" to set frontApp to name of first process whose frontmost is true' \
    -e 'if frontApp is "Google Chrome" then' \
    -e 'tell application "Google Chrome" to if (count of windows) > 0 then return "Google Chrome | " & (title of active tab of front window) & " | " & (URL of active tab of front window)' \
    -e 'else if frontApp is "Safari" then' \
    -e 'tell application "Safari" to if (count of windows) > 0 then return "Safari | " & (name of front document) & " | " & (URL of current tab of front window)' \
    -e 'end if' 2>/dev/null || echo "No supported browser URL captured"
}

cursor_snippet() {
  python3 - <<'PY'
import json
from pathlib import Path

path = Path("/Users/pvalastro/.cursor/projects/Users-pvalastro-Desktop-cursor-project/agent-transcripts")
files = sorted(path.rglob("*.jsonl"), key=lambda p: p.stat().st_mtime, reverse=True)
if not files:
    print("- No transcript data found.")
    raise SystemExit

messages = []
raw_tail = files[0].read_text(errors="ignore").splitlines()[-8:]
for line in files[0].read_text(errors="ignore").splitlines()[-250:]:
    try:
        obj = json.loads(line)
    except Exception:
        continue
    role = obj.get("role")
    content = obj.get("content")
    if role not in ("user", "assistant") or not content:
        continue
    if isinstance(content, list):
        txt = " ".join(str(c.get("text", "")) for c in content if isinstance(c, dict))
    else:
        txt = str(content)
    txt = " ".join(txt.split())
    if txt:
        messages.append((role, txt[:220] + ("..." if len(txt) > 220 else "")))

if messages:
    for role, txt in messages[-4:]:
        print(f"- {role}: {txt}")
else:
    for line in raw_tail[-4:]:
        clean = " ".join(line.split())
        print(f"- transcript: {clean[:220]}")
PY
}

entry=0
while [ "$entry" -lt "$MAX_ENTRIES" ]; do
  entry=$((entry + 1))
  ts="$(date '+%Y-%m-%d %H:%M:%S %Z')"
  app="$(frontmost_app)"
  browser="$(browser_context)"
  snippet="$(cursor_snippet)"

  {
    echo "## Entry ${entry} - ${ts}"
    echo
    echo "- Frontmost app: ${app}"
    echo "- Browser context: ${browser}"
    echo "- Cursor snippet:"
    echo "${snippet}"
    echo
    echo "---"
    echo
  } >>"$OUTPUT_FILE"

  sleep "$INTERVAL_SECONDS"
done

