/**
 * Parses `Peter's data day one.md` (peter-usage-monitor.sh output).
 */

function parseTranscriptLine(line) {
  try {
    const obj = JSON.parse(line)
    const role = obj?.role
    if (role === 'user' || role === 'assistant') return role
  } catch {
    /* ignore */
  }
  return null
}

function classifyFrontmost(app) {
  const a = (app || '').trim()
  if (!a) return 'unknown'
  if (/cursor/i.test(a)) return 'cursor'
  if (/chrome|safari|firefox|edge|brave|opera/i.test(a)) return 'browser'
  return 'other'
}

function browserLabel(context) {
  const c = (context || '').trim()
  if (!c) return null
  const parts = c.split('|').map((s) => s.trim())
  if (parts.length >= 2) return parts[1]
  if (c.length > 80) return `${c.slice(0, 77)}…`
  return c
}

export function parseUsageLogMarkdown(md) {
  const titleLine = md.match(/^#\s+(.+)$/m)
  const generatedLine = md.match(/^Generated by\s+(.+)$/m)
  const meta = {
    logTitle: titleLine ? titleLine[1].trim() : null,
    generatedBy: generatedLine ? generatedLine[1].trim() : null,
  }

  const blocks = md.split(/\n(?=## Entry \d)/).filter((b) => b.trim().startsWith('## Entry'))

  const entries = []
  let userMsgs = 0
  let assistantMsgs = 0

  for (const block of blocks) {
    const header = block.match(/^## Entry (\d+) - (.+)$/m)
    if (!header) continue

    const frontMatch = block.match(/^- Frontmost app:\s*(.*)$/m)
    const browserMatch = block.match(/^- Browser context:\s*(.*)$/m)
    const frontmost = frontMatch ? frontMatch[1].trim() : ''
    const browserContext = browserMatch ? browserMatch[1].trim() : ''

    const transcriptLines = [...block.matchAll(/^- transcript:\s*(.+)$/gm)].map((m) => m[1])
    for (const tl of transcriptLines) {
      const r = parseTranscriptLine(tl)
      if (r === 'user') userMsgs += 1
      else if (r === 'assistant') assistantMsgs += 1
    }

    const when = header[2].trim()
    const dateMs = Date.parse(when.replace(/ EDT$| EST$/, '')) || null

    entries.push({
      entryNum: Number(header[1], 10),
      when,
      dateMs,
      frontmost,
      browserContext,
      browserShort: browserLabel(browserContext),
      category: classifyFrontmost(frontmost),
      transcriptCount: transcriptLines.length,
    })
  }

  const catCounts = { cursor: 0, browser: 0, other: 0, unknown: 0 }
  for (const e of entries) {
    catCounts[e.category] = (catCounts[e.category] || 0) + 1
  }

  const total = entries.length || 1
  const pct = (n) => Math.round((100 * n) / total)

  const firstMs = entries.reduce((m, e) => (e.dateMs != null && (m == null || e.dateMs < m) ? e.dateMs : m), null)
  const lastMs = entries.reduce((m, e) => (e.dateMs != null && (m == null || e.dateMs > m) ? e.dateMs : m), null)

  const transcriptTotal = userMsgs + assistantMsgs
  const userPct = transcriptTotal ? Math.round((100 * userMsgs) / transcriptTotal) : 0

  return {
    meta,
    entries,
    summary: {
      totalEntries: entries.length,
      firstMs,
      lastMs,
      catCounts,
      cursorPct: pct(catCounts.cursor),
      browserPct: pct(catCounts.browser),
      otherPct: pct(catCounts.other + catCounts.unknown),
      userMsgs,
      assistantMsgs,
      userPct,
      assistantPct: transcriptTotal ? 100 - userPct : 0,
    },
  }
}

/** SVG donut segment: start/end angles in radians, center cx,cy, outer R, inner r */
export function donutArc(cx, cy, R, r, a0, a1) {
  const x0 = cx + R * Math.cos(a0)
  const y0 = cy + R * Math.sin(a0)
  const x1 = cx + R * Math.cos(a1)
  const y1 = cy + R * Math.sin(a1)
  const x0i = cx + r * Math.cos(a1)
  const y0i = cy + r * Math.sin(a1)
  const x1i = cx + r * Math.cos(a0)
  const y1i = cy + r * Math.sin(a0)
  const large = a1 - a0 > Math.PI ? 1 : 0
  return [
    `M ${x0} ${y0}`,
    `A ${R} ${R} 0 ${large} 1 ${x1} ${y1}`,
    `L ${x0i} ${y0i}`,
    `A ${r} ${r} 0 ${large} 0 ${x1i} ${y1i}`,
    'Z',
  ].join(' ')
}
